version: "3"
services:
  opensearch:
    image: opensearchproject/opensearch:1.1.0
    ports:
      - 9200:9200
      - 9600:9600
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "discovery.type=single-node"